#
# Copyright (C) 2026  Makai Systems. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

FIND_PACKAGE(lcms2 CONFIG QUIET)

IF(TARGET lcms2::lcms2)
  SET_PROPERTY(
    TARGET lcms2::lcms2
    PROPERTY IMPORTED_GLOBAL TRUE
  )
  IF(NOT TARGET lcms)
    ADD_LIBRARY(lcms ALIAS lcms2::lcms2)
  ENDIF()
ELSE()
  FIND_PACKAGE(PkgConfig REQUIRED)
  PKG_CHECK_MODULES(LCMS2 REQUIRED IMPORTED_TARGET lcms2)
  SET_PROPERTY(
    TARGET PkgConfig::LCMS2
    PROPERTY IMPORTED_GLOBAL TRUE
  )
  IF(NOT TARGET lcms)
    ADD_LIBRARY(lcms ALIAS PkgConfig::LCMS2)
  ENDIF()
ENDIF()
