# OpenJPEG via system (brew/pkg-config)

FIND_PACKAGE(PkgConfig REQUIRED)
PKG_CHECK_MODULES(OPENJP2 REQUIRED IMPORTED_TARGET libopenjp2)

IF(NOT TARGET OpenJpeg::OpenJpeg)
  ADD_LIBRARY(OpenJpeg::OpenJpeg INTERFACE IMPORTED GLOBAL)
  SET_PROPERTY(
    TARGET OpenJpeg::OpenJpeg
    PROPERTY INTERFACE_LINK_LIBRARIES PkgConfig::OPENJP2
  )
  FIND_PATH(
    OPENJP2_INCLUDE_DIR
    NAMES "openjpeg.h"
    HINTS ${OPENJP2_INCLUDEDIR} ${OPENJP2_INCLUDE_DIRS}
  )
  IF(OPENJP2_INCLUDE_DIR)
    SET_PROPERTY(
      TARGET OpenJpeg::OpenJpeg
      PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${OPENJP2_INCLUDE_DIR}"
    )
  ENDIF()
ENDIF()
