/* -LICENSE-START-
** Copyright (c) 2025 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
**
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

#pragma once

#include <cassert>
#include <cstring>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>

#if defined(_WIN32)
#ifndef BLACKMAGIC_RAW_API_DIR
#define BLACKMAGIC_RAW_API_DIR "../../../../Win/Libraries/"
#endif
#include "BlackmagicRawAPIDispatch.h"
#include <oleauto.h>
#include <wchar.h>
#include <wtypes.h>
#elif defined(__APPLE__)
#ifndef BLACKMAGIC_RAW_API_DIR
#define BLACKMAGIC_RAW_API_DIR "../../../../Mac/Libraries/"
#endif
#include <CoreFoundation/CoreFoundation.h>
#define IID_IUnknown (REFIID){0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46}

static inline bool operator==(const REFIID& iid1, const REFIID& iid2) { return std::memcmp(&iid1, &iid2, sizeof(REFIID)) == 0; }
#else
#ifndef BLACKMAGIC_RAW_API_DIR
#define BLACKMAGIC_RAW_API_DIR "../../../../Linux/Libraries/"
#endif
#include "LinuxCOM.h"
#endif

#if defined(_DEBUG) || defined(DEBUG)
#define VERIFY(condition) assert(SUCCEEDED(condition))
#else
#define VERIFY(condition) condition
#endif

namespace COM
{

    struct Initialiser
    {
        Initialiser()
        {
#ifdef _WIN32
            if (::CoInitializeEx(nullptr, COINIT_MULTITHREADED) != S_OK)
                throw std::runtime_error("Initialization of COM failed!");
#endif
        }

        ~Initialiser()
        {
#ifdef _WIN32
            ::CoUninitialize();
#endif
        }
    };

#if defined(_WIN32)
    using Bool = BOOL;
    using NativeString = BSTR;
    using SafeArray = SAFEARRAY;
    using SafeArrayBound = SAFEARRAYBOUND;
    using Variant = VARIANT;
    using VariantType = VARTYPE;
#elif defined(__APPLE__)
    using Bool = bool;
    using NativeString = CFStringRef;
    using SafeArray = SafeArray;
    using SafeArrayBound = SafeArrayBound;
    using Variant = Variant;
    using VariantType = BlackmagicRawVariantType;
#else
    using Bool = bool;
    using NativeString = const char*;
    using SafeArray = SafeArray;
    using SafeArrayBound = SafeArrayBound;
    using Variant = Variant;
    using VariantType = BlackmagicRawVariantType;
#endif

    template <typename T> class OwningPtr
    {
    public:
        OwningPtr() = default;

        explicit OwningPtr(T* ptr)
            : m_ptr(ptr)
        {
            // We are not calling AddRef because we're only taking ownership
            // of a pointer that was created elsewhere as per COM semantics.
        }

        ~OwningPtr()
        {
            // We own this object now so Release must be called.
            if (m_ptr)
                m_ptr->Release();
        }

        OwningPtr(const OwningPtr&) = delete;
        OwningPtr& operator=(const OwningPtr&) = delete;

        OwningPtr(OwningPtr&& other)
            : m_ptr(std::exchange(other.m_ptr, nullptr))
        {
        }

        OwningPtr& operator=(OwningPtr&& other)
        {
            if (m_ptr)
                m_ptr->Release();

            m_ptr = std::exchange(other.m_ptr, nullptr);

            return *this;
        }

        T* operator->() const { return m_ptr; }

        operator T*() const { return m_ptr; }

        T** outArg()
        {
            assert(m_ptr == nullptr);
            return &m_ptr;
        }

    private:
        T* m_ptr = nullptr;
    };

#if defined(_WIN32)
    inline NativeString NativeStringCopyUTF8(NativeString str) noexcept { return str ? SysAllocString(str) : nullptr; }

    inline NativeString NativeStringCopyUTF8(const char* str) noexcept
    {
        if (!str)
            return nullptr;

        const int wideCharCount = MultiByteToWideChar(CP_UTF8, 0, str, -1, nullptr, 0);

        BSTR strCopy = SysAllocStringLen(nullptr, wideCharCount);
        if (strCopy != nullptr)
            MultiByteToWideChar(CP_UTF8, 0, str, -1, strCopy, wideCharCount);

        return strCopy;
    }

    inline void NativeStringFree(NativeString str) noexcept
    {
        if (str)
            SysFreeString(str);
    }

    inline std::string NativeStringAsUTF8StdString(NativeString str) noexcept
    {
        if (!str)
            return {};

        const UINT strLength = SysStringLen(str);

        const int utf8Length = WideCharToMultiByte(CP_UTF8, 0, str, strLength, nullptr, 0, nullptr, nullptr);

        std::string utf8String(utf8Length, '\0');
        if (utf8Length > 0)
            WideCharToMultiByte(CP_UTF8, 0, str, strLength, utf8String.data(), utf8Length, nullptr, nullptr);

        return utf8String;
    }
#elif defined(__APPLE__)
    inline NativeString NativeStringCopyUTF8(NativeString str) noexcept
    {
        return str ? CFStringCreateCopy(kCFAllocatorDefault, str) : nullptr;
    }

    inline NativeString NativeStringCopyUTF8(const char* str) noexcept
    {
        return str ? CFStringCreateWithCString(kCFAllocatorDefault, str, kCFStringEncodingUTF8) : nullptr;
    }

    inline void NativeStringFree(NativeString str) noexcept
    {
        if (str)
        {
            assert(CFGetRetainCount(str) > 0);
            CFRelease(str);
        }
    }

    inline std::string NativeStringAsUTF8StdString(NativeString str) noexcept
    {
        const size_t length = CFStringGetLength(str);
        if (length == 0)
            return {};

        const CFIndex maxSize = CFStringGetMaximumSizeForEncoding(length, kCFStringEncodingUTF8) + 1;

        const char* utf8 = CFStringGetCStringPtr(str, kCFStringEncodingUTF8);
        if (utf8)
            return utf8;

        std::string utf8str(maxSize, '\0');
        CFStringGetCString(str, utf8str.data(), static_cast<CFIndex>(maxSize), kCFStringEncodingUTF8);
        return utf8str;
    }
#else
    inline void NativeStringFree(NativeString str) noexcept
    {
        if (str)
            delete[] str;
    }

    inline NativeString NativeStringCopyUTF8(NativeString str) noexcept
    {
        return str ? std::strcpy(new char[std::strlen(str) + 1], str) : nullptr;
    }

    inline std::string NativeStringAsUTF8StdString(NativeString str) noexcept { return str ? std::string(str) : std::string(); }
#endif

    class String
    {
    public:
        String() = default;

        ~String() { NativeStringFree(m_str); }

        explicit String(const char* str) noexcept
            : m_str(NativeStringCopyUTF8(str))
        {
        }

        template <typename T = NativeString, typename = std::enable_if_t<!std::is_same<T, const char*>::value>>
        explicit String(T str) noexcept
            : m_str(NativeStringCopyUTF8(str))
        {
        }

        String(const String&) noexcept = delete;
        String(String&&) noexcept = delete;

        String& operator=(const String&) noexcept = delete;
        String& operator=(String&&) noexcept = delete;

        operator NativeString() const noexcept { return m_str; }

        std::string str() const noexcept { return NativeStringAsUTF8StdString(m_str); }

        NativeString* outArg() noexcept
        {
            NativeStringFree(m_str);
            return &m_str;
        }

        NativeString release() noexcept { return std::exchange(m_str, nullptr); }

    private:
        NativeString m_str = {};
    };

} // namespace COM
