name: UTV Windows

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip_deps_cache:
        type: string
        default: 'false'
      qt5_modules:
        type: string
      full_matrix:
        type: string
        default: 'true'
      run_debug:
        type: string
        default: 'true'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Windows Build'
    runs-on: windows-2022
    env:
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/build-windows

